"""initial system of record.

Revision ID: 20260920_0001
Revises: 
Create Date: 2026-09-21 07:50:41.222409+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '20260920_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callers',
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=128), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callers')),
    sa.UniqueConstraint('phone_hash', name=op.f('uq_callers_phone_hash'))
    )
    op.create_table('institutes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutes')),
    sa.UniqueConstraint('code', name=op.f('uq_institutes_code'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id_occurred_at'), 'audit_logs', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type_resource_id_occurred_at'), 'audit_logs', ['resource_type', 'resource_id', 'occurred_at'], unique=False)
    op.create_table('branches',
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], name=op.f('fk_branches_institute_id_institutes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('institute_id', 'code', name=op.f('uq_branches_institute_id_code'))
    )
    op.create_index(op.f('ix_branches_institute_id_is_active'), 'branches', ['institute_id', 'is_active'], unique=False)
    op.create_table('calls',
    sa.Column('caller_id', sa.UUID(), nullable=True),
    sa.Column('provider_call_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_stage', sa.String(length=64), nullable=True),
    sa.Column('booking_status', sa.String(length=32), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name=op.f('ck_calls_direction')),
    sa.CheckConstraint("status IN ('pending', 'ringing', 'in_progress', 'completed', 'failed', 'cancelled', 'no_answer', 'busy')", name=op.f('ck_calls_status')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_calls_currency_length')),
    sa.CheckConstraint('total_cost >= 0', name=op.f('ck_calls_total_cost_nonnegative')),
    sa.ForeignKeyConstraint(['caller_id'], ['callers.id'], name=op.f('fk_calls_caller_id_callers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('provider_call_id', name=op.f('uq_calls_provider_call_id'))
    )
    op.create_index(op.f('ix_calls_caller_id_created_at'), 'calls', ['caller_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_calls_started_at'), 'calls', ['started_at'], unique=False)
    op.create_index(op.f('ix_calls_status_created_at'), 'calls', ['status', 'created_at'], unique=False)
    op.create_table('courses',
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], name=op.f('fk_courses_institute_id_institutes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('institute_id', 'code', name=op.f('uq_courses_institute_id_code'))
    )
    op.create_index(op.f('ix_courses_institute_id_is_active'), 'courses', ['institute_id', 'is_active'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('appointment_slots',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'held', 'booked', 'blocked', 'cancelled')", name=op.f('ck_appointment_slots_status')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_appointment_slots_capacity_positive')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_appointment_slots_time_order')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_appointment_slots_branch_id_branches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_slots')),
    sa.UniqueConstraint('branch_id', 'appointment_date', 'start_time', name=op.f('uq_appointment_slots_branch_id_appointment_date_start_time'))
    )
    op.create_index(op.f('ix_appointment_slots_branch_id_appointment_date_status_start_time'), 'appointment_slots', ['branch_id', 'appointment_date', 'status', 'start_time'], unique=False)
    op.create_table('branch_courses',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_courses_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_branch_courses_course_id_courses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('branch_id', 'course_id', name=op.f('pk_branch_courses'))
    )
    op.create_table('call_events',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('conversation_stage', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_events_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_call_events_idempotency_key'))
    )
    op.create_index(op.f('ix_call_events_call_id_occurred_at'), 'call_events', ['call_id', 'occurred_at'], unique=False)
    op.create_table('call_turns',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=16), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('conversation_stage', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("speaker IN ('caller', 'agent', 'system')", name=op.f('ck_call_turns_speaker')),
    sa.CheckConstraint('latency_ms >= 0', name=op.f('ck_call_turns_latency_ms_nonnegative')),
    sa.CheckConstraint('turn_number > 0', name=op.f('ck_call_turns_turn_number_positive')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_turns_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_turns')),
    sa.UniqueConstraint('call_id', 'turn_number', name=op.f('uq_call_turns_call_id_turn_number'))
    )
    op.create_index(op.f('ix_call_turns_call_id_created_at'), 'call_turns', ['call_id', 'created_at'], unique=False)
    op.create_table('counsellors',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_counsellors_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_counsellors_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counsellors')),
    sa.UniqueConstraint('branch_id', 'employee_code', name=op.f('uq_counsellors_branch_id_employee_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_counsellors_user_id'))
    )
    op.create_index(op.f('ix_counsellors_branch_id_is_active'), 'counsellors', ['branch_id', 'is_active'], unique=False)
    op.create_table('recordings',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'available', 'deleted', 'failed')", name=op.f('ck_recordings_status')),
    sa.CheckConstraint('duration_ms >= 0', name=op.f('ck_recordings_duration_ms_nonnegative')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_recordings_size_bytes_nonnegative')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_recordings_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('storage_provider', 'object_key', name=op.f('uq_recordings_storage_provider_object_key'))
    )
    op.create_index(op.f('ix_recordings_retention_until_status'), 'recordings', ['retention_until', 'status'], unique=False)
    op.create_table('appointments',
    sa.Column('caller_id', sa.UUID(), nullable=True),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('counsellor_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('booked', 'confirmed', 'completed', 'cancelled', 'no_show')", name=op.f('ck_appointments_status')),
    sa.ForeignKeyConstraint(['branch_id', 'appointment_date', 'start_time'], ['appointment_slots.branch_id', 'appointment_slots.appointment_date', 'appointment_slots.start_time'], name=op.f('fk_appointments_branch_id_appointment_date_start_time_appointment_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_appointments_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['caller_id'], ['callers.id'], name=op.f('fk_appointments_caller_id_callers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counsellor_id'], ['counsellors.id'], name=op.f('fk_appointments_counsellor_id_counsellors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_appointments_course_id_courses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_branch_id_appointment_date_status'), 'appointments', ['branch_id', 'appointment_date', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_caller_id_appointment_date'), 'appointments', ['caller_id', 'appointment_date'], unique=False)
    op.create_index('uq_appointments_active_slot', 'appointments', ['branch_id', 'appointment_date', 'start_time'], unique=True, postgresql_where=sa.text("status IN ('booked', 'confirmed')"))
    op.create_table('provider_usage',
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('measured_units', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unit_name', sa.String(length=64), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("service IN ('telephony', 'stt', 'llm', 'tts')", name=op.f('ck_provider_usage_service')),
    sa.CheckConstraint('measured_units >= 0', name=op.f('ck_provider_usage_measured_units_nonnegative')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_provider_usage_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turn_id'], ['call_turns.id'], name=op.f('fk_provider_usage_turn_id_call_turns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_usage')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_provider_usage_idempotency_key'))
    )
    op.create_index(op.f('ix_provider_usage_call_id_service_occurred_at'), 'provider_usage', ['call_id', 'service', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_provider_usage_provider_service_occurred_at'), 'provider_usage', ['provider', 'service', 'occurred_at'], unique=False)
    op.create_table('safety_events',
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('rule', sa.String(length=128), nullable=True),
    sa.Column('original_category', sa.String(length=128), nullable=True),
    sa.Column('replacement_type', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_safety_events_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turn_id'], ['call_turns.id'], name=op.f('fk_safety_events_turn_id_call_turns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_events'))
    )
    op.create_index(op.f('ix_safety_events_call_id_created_at'), 'safety_events', ['call_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_safety_events_rule_created_at'), 'safety_events', ['rule', 'created_at'], unique=False)
    op.create_table('call_costs',
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('provider_usage_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pricing_version', sa.String(length=128), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_call_costs_amount_nonnegative')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_call_costs_currency_length')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_call_costs_quantity_nonnegative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_call_costs_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_costs_call_id_calls'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_usage_id'], ['provider_usage.id'], name=op.f('fk_call_costs_provider_usage_id_provider_usage'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_costs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_call_costs_idempotency_key'))
    )
    op.create_index(op.f('ix_call_costs_call_id_occurred_at'), 'call_costs', ['call_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_call_costs_provider_service_occurred_at'), 'call_costs', ['provider', 'service', 'occurred_at'], unique=False)
    op.create_table('followup_jobs',
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_owner', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'dead_letter')", name=op.f('ck_followup_jobs_status')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_followup_jobs_attempts_nonnegative')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_followup_jobs_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_followup_jobs_call_id_calls'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followup_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_followup_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_followup_jobs_status_available_at'), 'followup_jobs', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followup_jobs_status_available_at'), table_name='followup_jobs')
    op.drop_table('followup_jobs')
    op.drop_index(op.f('ix_call_costs_provider_service_occurred_at'), table_name='call_costs')
    op.drop_index(op.f('ix_call_costs_call_id_occurred_at'), table_name='call_costs')
    op.drop_table('call_costs')
    op.drop_index(op.f('ix_safety_events_rule_created_at'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_call_id_created_at'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_provider_usage_provider_service_occurred_at'), table_name='provider_usage')
    op.drop_index(op.f('ix_provider_usage_call_id_service_occurred_at'), table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_index('uq_appointments_active_slot', table_name='appointments', postgresql_where=sa.text("status IN ('booked', 'confirmed')"))
    op.drop_index(op.f('ix_appointments_caller_id_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_branch_id_appointment_date_status'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_recordings_retention_until_status'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_counsellors_branch_id_is_active'), table_name='counsellors')
    op.drop_table('counsellors')
    op.drop_index(op.f('ix_call_turns_call_id_created_at'), table_name='call_turns')
    op.drop_table('call_turns')
    op.drop_index(op.f('ix_call_events_call_id_occurred_at'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_table('branch_courses')
    op.drop_index(op.f('ix_appointment_slots_branch_id_appointment_date_status_start_time'), table_name='appointment_slots')
    op.drop_table('appointment_slots')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_courses_institute_id_is_active'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_calls_status_created_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_started_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_id_created_at'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_branches_institute_id_is_active'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_resource_type_resource_id_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id_occurred_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('institutes')
    op.drop_table('callers')
    # ### end Alembic commands ###
