"""Local call capture — the pipecat adapter for `roma.postcall` (docs/09 option 2).

docs/09 offers two capture methods and insists one be chosen explicitly. We capture
locally: the audio never leaves our infrastructure, which is what the Vadodara self-host
decision and PII locality both ask for. Twilio never holds a copy.

## The capture processor is pipecat's, not ours

`AudioBufferProcessor` already solves the hard part — dual-leg capture, stereo
interleaving, auto-stop on `EndFrame`/`CancelFrame`, and (the non-obvious one) wall-clock
**silence-gap alignment**, which pads Roma's bursty TTS so it sits at the right offset
against the lead's continuous 20ms stream. Hand-rolling that alignment is how you get a
recording where both speakers appear to talk at once. We supply only the file sink.

## One stereo file, headerless while the call runs

Channel 0 is the lead, channel 1 is Roma. That reconciles CLAUDE.md's "separate legs per
speaker" with docs/09's singular `{date}/{call_sid}.{ext}` — the legs stay separable
inside one artifact.

On disk during the call it is **raw interleaved PCM16LE**, not WAV, and that is a
deliberate crash-safety choice: a WAV header carries a frame count that is only patched
when the file is closed, so a `SIGKILL` mid-call leaves a file that lies about its own
length. Raw PCM has no header, so every byte already on disk is valid audio and the worst
case is losing whatever had not been flushed. The worker packages it as WAV later, where a
crash is merely retriable.

## Where it sits in the pipeline

**After `transport.output()`**, never before. Four independent reasons, and every one of
them fails if it sits earlier:

1. `BaseOutputTransport` pushes an `OutputAudioRawFrame` downstream only *after*
   `write_audio_frame` has succeeded — so downstream is the only place that sees audio the
   lead actually heard.
2. On an `InterruptionFrame` the output sender cancels its audio task and flushes its
   queue; cancelled TTS never travels downstream. Placed earlier, the recording would
   contain speech that was interrupted and never played — worthless as a compliance record.
3. The gap-fill alignment uses `time.monotonic()` deltas and needs the output transport's
   real-time pacing. Upstream, TTS arrives in bursts and Roma's speech compresses to the
   front of the timeline.
4. `BotStartedSpeakingFrame` / `BotStoppedSpeakingFrame` are *generated by* the output
   transport, so the buffer processor's speaking guards are dead without it upstream.

The lead's leg still arrives downstream: `InputAudioRawFrame` is a `SystemFrame`, the STT
service passes it through (`audio_passthrough` defaults True), and `BaseOutputTransport`
forwards system frames on. That is a load-bearing pipecat default — `test_recorder.py`
pins it, because if a version bump ever flips it the lead's side vanishes in silence.
"""

import logging
import os
from datetime import UTC, datetime
from pathlib import Path

from pipecat.processors.audio.audio_buffer_processor import AudioBufferProcessor

from roma.postcall.paths import media_dir, open_private

_log = logging.getLogger("roma.telephony")

RECORDING_SAMPLE_RATE = 8000
RECORDING_CHANNELS = 2
RECORDING_SAMPLE_WIDTH = 2
RECORDING_EXT = ".s16le"

_BYTES_PER_SECOND = RECORDING_SAMPLE_RATE * RECORDING_SAMPLE_WIDTH * RECORDING_CHANNELS
FLUSH_BYTES = _BYTES_PER_SECOND * 5


class CallRecorder:
    """An append-only file sink for one call's captured audio.

    Not a `FrameProcessor` — `attach_recorder` wires it to pipecat's buffer processor.
    Keeping it a plain object means the file mechanics are testable without a pipeline.
    """

    def __init__(self, path, *, started_at: "datetime | None" = None) -> None:
        self.path = Path(path)
        self.started_at = started_at or datetime.now(UTC)
        self.bytes_written = 0
        self.failed = False
        self._fh = None
        self._closed = False

    def _ensure_open(self):
        if self._fh is None and not self._closed:
            self._fh = open_private(self.path, "wb")
        return self._fh

    def append(self, pcm: bytes) -> None:
        """Write captured audio. Never raises — a disk problem must not end a live call."""
        if self._closed or self.failed or not pcm:
            return
        try:
            fh = self._ensure_open()
            fh.write(pcm)
            self.bytes_written += len(pcm)
        except Exception as exc:  # noqa: BLE001 — recording must never kill a call (docs/08)
            self.failed = True
            _log.error(
                "recording failed after %d bytes (%s); call continues without capture",
                self.bytes_written,
                type(exc).__name__,
            )

    def close(self) -> None:
        """Flush and fsync. Idempotent — teardown may call it more than once."""
        if self._closed:
            return
        self._closed = True
        fh, self._fh = self._fh, None
        if fh is None:
            return
        try:
            fh.flush()
            os.fsync(fh.fileno())
        except Exception as exc:  # noqa: BLE001 — best effort; the bytes are already there
            _log.error("recording close/fsync failed (%s)", type(exc).__name__)
        finally:
            try:
                fh.close()
            except Exception:  # noqa: BLE001
                pass

    def audio_secs(self) -> float:
        """Captured duration derived from the byte count."""
        return self.bytes_written / _BYTES_PER_SECOND if _BYTES_PER_SECOND else 0.0

    def is_empty(self) -> bool:
        return self.bytes_written == 0

    def relative_ref(self, root) -> str:
        """The job's `recording_ref`: a path RELATIVE to the media root, so relocating the
        data directory is a config change rather than a rewrite of every queued job."""
        try:
            return self.path.relative_to(Path(root)).as_posix()
        except ValueError:
            return self.path.name


def build_recorder(settings, call_sid: str, *, now: "datetime | None" = None) -> CallRecorder:
    """A recorder for one call, at `{media_dir}/{date}/{call_sid}.s16le`."""
    now = now or datetime.now(UTC)
    root = media_dir(settings)
    path = root / now.strftime("%Y-%m-%d") / f"{call_sid}{RECORDING_EXT}"
    return CallRecorder(path, started_at=now)


def attach_recorder(recorder: CallRecorder) -> AudioBufferProcessor:
    """Build the pipecat capture processor and route its audio into `recorder`."""
    processor = AudioBufferProcessor(
        sample_rate=RECORDING_SAMPLE_RATE,
        num_channels=RECORDING_CHANNELS,
        buffer_size=FLUSH_BYTES,
        auto_start_recording=True,
    )

    @processor.event_handler("on_audio_data")
    async def _on_audio(_processor, audio: bytes, _sample_rate: int, _num_channels: int):
        recorder.append(audio)

    return processor


__all__ = [
    "CallRecorder",
    "build_recorder",
    "attach_recorder",
    "RECORDING_SAMPLE_RATE",
    "RECORDING_CHANNELS",
    "RECORDING_EXT",
    "FLUSH_BYTES",
]
